Repository ioled/Git_flow, pull requests merged in 2020-07, with the labels that each got.

#30 Pruenas 1
  README.md
  archivo.md
Labels: size/xl

#28 prueba 15
  README.md
Labels: size/m

#29 aprendiendo con ioled
  README.md
Labels: size/s
