Repository ioled/Git_flow, pull requests merged in 2021-07, with the labels that each got.

#37 feat: added cat meme
  README.md
  cat-meme.gif
Labels: size/s

#40 barto
  BARTO.jpg
  README.md
Labels: size/xl

#41 Creé el archivo nico.txt
  nico.txt
Labels: size/xs

#39 techi rules
  README.md
Labels: size/s

#43 F/nicolas branch
  README.md
  messi_borracho.png
  messi_pelado.png
  nico.txt
Labels: size/m
